<?php
$dados = "1-CC Iolanda	,
1-CC Ipiranga	,
1-CC Itaquera	,
1-CC Lapa	,
1-CC Mogi Das Cruzes	,
1-CC Nordestina	,
1-CC Osasco	,
1-CC Penha	,
1-CC Santa Cecilia	,
1-CC Santo André	,
1CC São Caetano	,
1-CC São Miguel	,
1-CC SBC	,
1-CC SBC I	,
1-CC SBC II	,
1-CC SBC III	,
1-CC Taboão da Serra	,
1-CC Tatuapé	,
1-CC Zona Sul I	,
1-Hospital e Maternidade Nossa Sra Rosário	,
1-Intermédica	,
2-A Saúde Clinica Médica	,
2-AME	,
2-AME AMBULATÓRIO MÉDICO	,
2-Associação Comercial	,
2-Assunção	,
2-Beneficiencia Portuguesa	,
2-Bio Center Laboratorio	,
2-BM Clínica Médica S/S LTDA	,
2-Cadi Centro de Analises	,
2-CE Clinica de Olhos	,
2-CECLIM-Centro Clínico Médico Ltda	,
2-Cedeco	,
2-Cedis 	,
2-CEMA	,
2-Cemeap	,
2-Centerclin	,
2-Centro clinico Santa Luzia	,
2-Centro Clinico Santa Maria	,
2-Centro de Oftalmologia	,
2-Centro Diagnostico Jd.Mar	,
2-Centro Fianose em Otorrinolagologia	,
2-Centro Médico Iolanda	,
2-Centro Paula Sousa 	,
2-Cerpo oftalmo	,
2-Cids	,
2-CIMED	,
2-Cli Fic Fisioterapia	,
2-Climeci 	,
2-Climep Assistência Médica	,
2-Clinica Anhembi	,
2-Clinica Cardiológica Dr Julio Abdala	,
2-Clinica Ceccto 	,
2-Clinica Clinimed Policlinica	,
2-Clinica de Fisioterapia	,
2-Clinica De Olhos 	,
2-Clinica de olhos Dr. Jaime	,
2-Clinica de Ouvido,Nariz e Garganta	,
2-Clinica Dionisio	,
2-Clinica Drª Aracili	,
2-Clinica Global Fisio	,
2-Clínica infantil do Tatuapé	,
2-Clinica Jardim Helena	,
2-Clínica Manzano de Otorrinolaringologia	,
2-Clinica Médica Vila Alpina	,
2-Clinica Medica Wajman	,
2-Clinica Oftalmologica	,
2-Clinica Ortopédica	,
2-Clinica Pedriatrica	,
2-Clinica Poá	,
2-Clinica Rubens  do val	,
2-Clinica Saint Nicholas	,
2-Clinica Santa Catarina	,
2-Clinica Santa Cecilia	,
2-Clinica São Lucas	,
2-Clinica São Miguel	,
2-Clínica Saúde Itaquá	,
2-Clinica Soler	,
2-Clinileste	,
2-CM São Gabriel	,
2-CMC Clinica Médica Cardiomol	,
2-CME Medina e trabalho	,
2-Consultório Médico 	,
2-Consultorio Oftalmológico Dr José Cicero	,
2-Consultótio Oftalmológico	,
2-CONSUMED- Dr Riad	,
2-Cosb Clinica de Olhos	,
2-CREMED	,
2-CRS	,
2-CT Clin	,
2-Daniele Campos Centrode Reabilitação	,
2-Day Hosp. Ermelino Matarazzo	,
2-Dr. Alfio Paglia	,
2-Diagnostico	,
2-Diagnosticos por imagens schiavon	,
2-DIGIMAGEM- Laboratório	,
2-Dimedi	,
2-Divisão Hospitalar 	,
2-Divisão Hospitalar SBC	,
2-Dr Camila A Magos	,
2-Dr Ernesto	,
2-Dr José  Luis	,
2-Dr Ricardo A Assal	,
2-Dr Ricardo Machado	,
2-Dr. Antonio J Bione	,
2-Dr. Francisco	,
2-Dr. Ghelfond Diagnóstico Médico	,
2-DR. Helio Yoshino	,
2-Dr. Itiro m Hatada	,
2-Dr. Wilian Monteiro	,
2-Dr.Admilsob Lemos Costa	,
2-DR.Antonio J Bione	,
2-Dr.Paulo A berchelli	,
2-Dra Cristina Nishikawara	,
2-Dra.Irene Tuccio	,
2-Dunacor	,
2-Endo Diagnóstico	,
2-Endolife Serv Médicos	,
2-Endomax	,
2-Endorino	,
2-Family Hospital	,
2-HBS-Hospital Bosque da Saude	,
2-Hospital	,
2-Hospital  Ipiranga	,
2-Hospital  Pró Mater Santo Antonio	,
2-Hospital A.C. Camargo	,
2-Hospital ABC	,
2-Hospital Albert Sabin	,
2-Hospital Alvorada	,
2-Hospital Aviccena 	,
2-Hospital Bom Clima	,
2-Hospital da Luz	,
2-Hospital das Clinicas Luzia de Pinho Melo	,
2-Hospital Dom Antonio de Alvarenga	,
2-Hospital Dr. Cristovão da Gama	,
2-Hospital e Marternidade Bartira	,
2-Hospital e Maternida Independencia	,
2-Hospital e Maternidade Ass.	,
2-Hospital e Maternidade Bartira	,
2-Hospital e Maternidade Central	,
2-Hospital e Maternidade Dr.Cristivão da Gama	,
2-Hospital e Maternidade Independencia	,
2-Hospital e Maternidade Jardins	,
2-Hospital e Maternidade São Camilo	,
2-Hospital e Maternidade São Miguel	,
2-Hospital e Pronto socorro 	,
2-Hospital esperança	,
2-Hospital Estadual Sapopemba	,
2-Hospital Estadual Vila alpina	,
2-Hospital Geral da Penha	,
2-Hospital Geral Pirajussara	,
2-Hospital Ipiranga	,
2-Hospital Itaquera	,
2-Hospital Mogi-Dor	,
2-Hospital Montemagno	,
2-Hospital Municipal	,
2-Hospital Pró Mater Santo Antonio	,
2-Hospital Santa Casa de Suzano	,
2-Hospital Santa Catarina	,
2-Hospital Santana	,
2-Hospital São Bernardo	,
2-Hospital São Leopoldo	,
2-Hospital Sepaco	,
2-Hospital Vasco da Gama 	,
2-Hospital Vitória	,
2-Hospital Santana	,
2-Hospital e Maternidade  Ass.	,
2-Hospital e Pronto socorro Itamaraty	,
2-IACTA Saúde	,
2-Imed	,
2-Imed Mogi	,
2-Imego Ginecologia / Obsteticia	,
2-IMOT	,
2-Independência	,
2-Instituto de Olhos São Miguel	,
2-Instituto Frei Garpar	,
2-Intermédica	,
2-Irmandade da Santa Casa de Misericórdia da Suzano	,
2-Istituto deMedicina Especializadade Guarulhos	,
2-Itamaraty	,
2-Lab. Deliberato de Ana clin. s/c	,
2-Laboratorio Lavoisier	,
2-Lin Imagem	,
2-Maternal&Baby Care	,
2-Medcor	,
2-Medina	,
2-Mello	,
2-MOGI-D´OR	,
2-NASA	,
2-Oftalmoclinica Paulista	,
2-Ophthal	,
2-Ortoplan	,
2-Otoclin	,
2-P S Itaquera	,
2-Policlinica Taboão	,
2-Prefeitura do Múnicípio de São Paulo	,
2-Pulsar Saude	,
2-Receituario de controle Especial	,
2-Renascença SP	,
2-Rhesus Medicina Auxiliar	,
2-Ricardo Machado	,
2-Rua: Tenente Luis	,
2-S.E.G.O.	,
2-Sagita 	,
2-San Paolo	,
2-Santa Amalia 	,
2-Santa Casa de Misericórdia de Mogi das Cruzes	,
2-Santa Casa de Suzano	,
2-Santa Helena	,
2-Sem Nome	,
2-Serviços Médicos RIO	,
2-SPDM Dermatologia	,
2-Umdi 	,
2-Unen	,
2-Unidade Nacional de Medicina	,
2-Unidade Santana de oftalmo	,
2-Vida clean	,
2-Vida Clinica Ltda	,
3-Autarquia Hospitalar Minicipal	,
3-Banco de Sangue Santa Marcelina	,
3-Centro de Oftalmologia	,
3-Centro de Saúde III Pref Joaquim R Coelho	,
3-Centro Referencia da Saúde da Mulher	,
3-Clinica  Pediatrica	,
3-Colsan	,
3-Cruz Azul de SP	,
3-Ermelino Matarazzo	,
3-HMU	,
3-Hospital Albert Sabin	,
3-Hospital Autarquia hospitalar	,
3-Hospital Brigadeiro	,
3-Hospital das Clinicas Luzia de Pinho Melo	,
3-Hospital de Poa	,
3-Hospital Dr Osiris Florindo Coelho	,
3-Hospital e PS Vila Iolanda	,
3-Hospital Esperança	,
3-Hospital Estadual Mario C.	,
3-Hospital Estadual Vila alpina	,
3-Hospital Geral de São Mateus	,
3-Hospital Geral de São Paulo	,
3-Hospital Geral Jesus Teixeira	,
3-Hospital Infantil Cândido Fortura	,
3-Hospital Municipal de Poá Dr. Guido Guida	,
3-Hospital Municipal Dr Waldomiro	,
3-Hospital Municipal Tide Setubal	,
3-Hospital Nossa Senhora Aparecida	,
3-Hospital Osiris Florindo	,
3-Hospital São Paulo	,
3-Hospital Vila Alpina Heva	,
3-Indenpendência	,
3-Instituto Brasileiro de Controle do câncer	,
3-NÃO CONSTA 	,
3-P.S. Municipal Julio Tupy	,
3-PA Clinica Geral	,
3-PA DR Gloria RS Bonfim	,
3-PA. Dr. Atualpa Girão Rabelo	,
3-Posto de Saude	,
3-Posto de saude Santa Marcelina	,
3-Pref. da Estânica Hidromineral de Poá	,
3-Prefeitura  Municipal De Suzano	,
3-Prefeitura de SP	,
3-Prefeitura Municipal De Suzano	,
3-Pronto Socorro Julio Tupi	,
3-Santa Casa de Misericórdia de Mogi das Cruzes	,
3-Santa casa de São Paulo	,
3-Santa casa de Suzano	,
3-Santa Casa Ermelino Matarazzo	,
3-Santa Inês	,
3-Secretaria do Estado de Saúde	,
3-Secretaria do Estado de Saúde	,
3-Secretaria Municipal da Saúde	,
3-Sem Nome	,
3-UBS Botujuru	,
3-UBS Curuça Velha	,
3-UBS Filomena Rosiello Guida	,
3-UBS Jd Universo	,
3-UBS Jd. Marica	,
3-UBS Jundiapeba	,
3-Ubs Parque São Bernado	,
3-UBS PQ Maria Helena	,
3-UBS Pq. Santa Rita	,
3-UBS Thersio	,
3-UBS Vila Jacuí	,
3-UBS Vila Suissa	,
3-UBS-Jardim Helian	,
3-Unidade Parque Regina	,
3-Unidade Pirajussara	,
3-USB DR. Ivanhoe Esposito	,
4-AMA	,
4-AMA  Texima	,
4-AMA Burgo Paulista	,
4-AMA Carmosina	,
4-AMA Chácara Cruzeiro do Sul	,
4-AMA Cidade Lider 	,
4-AMA Dr Tito Lopes	,
4-AMA Dr. Alipio Correa Netto 	,
4-AMA Eng.Goulart Dr. José Pires	,
4-AMA Ermelino Matarazzo	,
4-AMA Fazenda do Carmo	,
4-AMA Guaianases	,
4-AMA Hosp.da AMA	,
4-AMA Itaquaquecetuba	,
4-AMA Jardim Campos	,
4-AMA Jardim Etelvina	,
4-AMA Jardim Laranjeiras	,
4-AMA Jardim Nélia	,
4-AMA Jd. Brasilia	,
4-AMA Jd. Campos	,
4-AMA Jd. Três Marias	,
4-AMA Jd.Helena	,
4-AMA José  Bonifacio 3	,
4-AMA Juscelino	,
4-AMA Laranjeiras	,
4-AMA Padre Manoel da Nóbrega	,
4-AMA Parada 15 de novembro	,
4-AMA Parque Boturussu	,
4-AMA Parque Paulistano	,
4-AMA Prefeitura do Município de São Paulo	,
4-AMA Sapopemba	,
4-AMA Sitio da Casa Pintada	,
4-AMA Tatuapé	,
4-AMA Vila Iolanda	,
4-AMA Vila Silvia	,
4-AMA Waldomiro de Paula	,
4-Complexo hospitalar  Padre Bento De Guarulhos	,
4-Hospital da AMA	,
4-Hospital Geral Jesus Teixeira	,
4-Hospital Geral Pirajussara	,
4-Hospital Infantil Menino Jesus	,
4-Hospital Municipal de Poá	,
4-Hospital Municipal Dr Ignacio Proença Gouveia	,
4-Hospital Municipal Tide Setubal	,
4-Hospital Regional De Ferraz De Vasconcelos	,
4-Hospital Santa Marcelina	,
4-Irmandade Da Santa casa Misericórdia	,
4-PA Dr. Atualpa Girão Rabelo 	,
4-Policlínica Dona Luiza	,
4-Posto de Saude	,
4-Posto de Saude	,
4-Prefeitura Campo Limpo	,
4-Prefeitura de Biritiba Mirim	,
4-Prefeitura de Embu	,
4-Prefeitura de Itapecerica da Serra	,
4-Prefeitura de Mogi	,
4-Prefeitura de Santo André	,
4-Prefeitura de SBC	,
4-Prefeitura de SP	,
4-Prefeitura de Suzano	,
4-Prefeitura de Taboão	,
4-PSF Vila Cosmopilita	,
4-Secretária Municipal de Saúde	,
5-Associação Cartão Cristã	,
5-Associação Comercial	,
5-Associaçao Paulista De Medicina	,
5-Bioclinic	,
5-BR Diagnóstico e Estética	,
5-Cadi Centro de Analises	,
5-CECLIM Centro  Clinico Médico 	,
5-CEMO	,
5-Centro clinico Santa Luzia	,
5-Centro de diagn.Brasil	,
5-Centro médico Fugi	,
5-Centro Urologico	,
5-Cerpo Oftalmologia	,
5-Ciro Radiodiagnostico	,
5-clinica	,
5-Clinica Anhembi	,
5-Clinica de  Olhos do ABC	,
5-CLÍNICA DE SAÚDE BUCAL	,
5-Clinica dentária	,
5-Clinica Harissa	,
5-Clinica Imesu	,
5-Clinica Médica Dr.Miguel Cury	,
5-Clinica Médica Especializada Limes	,
5-Clinica Médica Vila Alpina	,
5-Clinica Odontologica	,
5-Clinica Odontologica Curcio	,
5-Clinica Odontologiva	,
5-Clinica oftalmoclinica s/c ltda	,
5-Clinica Poa Dor	,
5-Clinica Pró Saude	,
5-Clinica Soler	,
5-Clinica Vida Clean	,
5-CliniMed	,
5-Coe-Clínica de Odontologia e estética	,
5-Consul.Odont.Cid.Tradentes	,
5-Consultório Médico 	,
5-Consultorio Odontologico	,
5-Consultório Oftalmológico	,
5-Ctclin	,
5-Delboni Auriemo	,
5-Denise Hidalgo Pelicano	,
5-Dentista	,
5-DR .Paulo Spindola Costa	,
5-DR Sol Trubilhano	,
5-Dr. Décio M. B. kato	,
5-Dr.Ghelsonf Diagnósticos Médicos	,
5-DRª Denise Prates Maganha	,
5-Ed Ecografia Diagnóstica	,
5-Emiliano José Silva Mendes	,
5-Eptros	,
5-Escola 	,
5-Especialista em Pediatria	,
5-Fat 	,
5-Grupo SS LTDA	,
5-HMU	,
5-Hospirtal Vitoria	,
5-Hospital ABC	,
5-Hospital Albert Sabin	,
5-Hospital Avicena	,
5-Hospital Carlos Chagas	,
5-Hospital Central  de Guaianazes	,
5-Hospital e Matenidade 8 de Maio	,
5-Hospital e Maternidade São Miguel	,
5-Hospital e Maternidade Vidas	,
5-Hospital Ipiranga	,
5-Hospital Leforte	,
5-Hospital Luz	,
5-Hospital Metropolitano	,
5-Hospital Mogi-Dor	,
5-Hospital Montemagno	,
5-Hospital Santa Catarina	,
5-Hospital Santa Helena	,
5-Hospital Vitória	,
5-IACTA Saúde	,
5-IMEDI	,
5-IMOT	,
5-Inec Institutode neurologia e neurocirurgia	,
5-Instituto de olhos São Miguel	,
5-Limes Clinica médica especializada	,
5-Medical Imagem	,
5-Mogidonto	,
5-Não tem nome da clinica	,
5-Ophthal-Hospital Especializado	,
5-ORTOCITY	,
5-Poder Judiciario	,
5-Porto Seguro	,
5-S.E.G.O.	,
5-Samed	,
5-SAMIS	,
5-Santa Amalia 	,
5-São Luiz	,
5-Scan-Diagnósticos	,
5-Seisa	,
5-Sem Nome	,
5-Sepaco	,
5-Sistema Médico São Benedito	,
5-Spin-eco Unidade São caetano	,
5-Sta Casa de Misericórida Sto Amaro	,
5-Tranjan Centro de Oftalmológia	,
5-Ultra X	,
5-UN Diagnóstico	,
5-UNEN	,
5-Unidade Mista Taboão da Serra	,
5-Unidade Nacional de Medicina	,
5-UNIMED	,
5-Unimed ABC	,
5-Unimed Guarulhos	,
5-Vida clean	,
5-VidaClin Ltda	,
5-Vista Clinica	,
5-Vista Med
";

$array  =   explode(",",$dados);

$contador = count($array);

for ($i = 0; $i < $contador ; $i++)
{
    $array2 =   explode("-",$array[$i]);
    
    echo $array2[1];
    echo "<br/>";
    
    
}




?>